version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    hostname: "zookeeper"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    expose:
      - 9092
    hostname: "kafka"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  venda_veiculo:
    image: venda_veiculo
    build: .
    depends_on:
      - kafka
    ports:
      - "5001:5000"
    hostname: "venda_veiculo"
    volumes:
      - "./servicos/venda_veiculo:/workdir"
    command: python3 /workdir/servico.py

  estoque:
    image: estoque
    build: .
    depends_on:
      - kafka
    hostname: "estoque"
    volumes:
      - "./servicos/estoque:/workdir"
    command: python3 /workdir/servico.py

  preco:
    image: preco
    build: .
    depends_on:
      - kafka
    hostname: "preco"
    volumes:
      - "./servicos/preco:/workdir"
    command: python3 /workdir/servico.py

  pagamento:
    image: pagamento
    build: .
    depends_on:
      - kafka
    hostname: "pagamento"
    volumes:
      - "./servicos/pagamento:/workdir"
    command: python3 /workdir/servico.py

  nf:
    image: nf
    build: .
    depends_on:
      - kafka
    hostname: "nf"
    volumes:
      - "./servicos/nf:/workdir"
    command: python3 /workdir/servico.py